export const GADGETARIUM_USER_DATA = 'USER_DATA'

export const SORT = {
   NEW: 'NEW',
   DISCOUNT: 'DISCOUNT',
   DISCOUNT_UP_FIFTY: 'DISCOUNT_UP_FIFTY',
   DISCOUNT_DOWN_FIFTY: 'DISCOUNT_LOW_FIFTY',
   RECOMMEND: 'RECOMMEND',
   PRICE_ACS: 'PRICE_ACS',
   PRICE_DESC: 'PRICE_DESC',
}
