export const GADGETARIUM_USER_DATA = 'USER_DATA'
export const STEPPER_FORM_DATA_KEY = 'STEPPER_FORM_DATA'
export const GADGETARIUM_ADD_PRODUCT_DATA = 'GADGETARIUM_ADD_PRODUCT_DATA'

export const SORT = {
   NEW: 'NEW',
   DISCOUNT: 'DISCOUNT',
   DISCOUNT_UP_FIFTY: 'DISCOUNT_UP_FIFTY',
   DISCOUNT_DOWN_FIFTY: 'DISCOUNT_LOW_FIFTY',
   RECOMMEND: 'RECOMMEND',
   PRICE_ACS: 'PRICE_ACS',
   PRICE_DESC: 'PRICE_DESC',
}

export const STATUS = {
   ON_SALE: 'ON_SALE',
   WISH_LIST: 'WISH_LIST',
   BASKET: 'BASKET',
}
